on:
  push:
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

name: Build and Lint
jobs:
  lint:
    name: ESLint style check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmInstall
        with:
          cwd: '.'
          enable-corepack: false

      - name: Run eslint
        run: pnpm run lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(eslint): fixed eslint style format [skip ci]"

  appbuild:
    name: Build apps
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmInstall
        with:
          cwd: '.'
          enable-corepack: false

      - name: Build apps
        run: pnpm run build:apps --summarize

      - name: Summarize Turborepo Output
        uses: ./packages/actions/src/turboSummary

  packagebuild:
    name: Build packages
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmInstall
        with:
          cwd: '.'
          enable-corepack: false

      - name: Build pacakges
        run: pnpm run build:packages --summarize

      - name: Summarize Turborepo Output
        uses: ./packages/actions/src/turboSummary
